### ISSUE TITLE
TRUE/FALSE flip in MA plot featured in §1.5 Diagnosing cell type loss

### ISSUE THREAD

**Issue by PeteHaitch** [OSCA-source/OSCA.advanced#10]
Think `kept` and `lost` should be reversed.

https://github.com/OSCA-source/OSCA.advanced/blob/95308a3135c4aba496573fd53a5d0c61f3ec0d24/inst/book/more-qc.Rmd#L188-L190

**Comment by PeteHaitch** [comment]
@lgeistlinger I cherry-picked this fix to the `RELEASE_3_16` branch, too (d5be3661503782c75992115bde0a67c5aa76e23e).
I also updated the `DESCRIPTION` in the `RELEASE_3_16` branch to reflect that you are the maintainer of this book (31b60edf15ddd45a037c4794adef7aecb8ca6996).

**Comment by lgeistlinger** [comment]
Thanks @PeteHaitch!
