### ISSUE TITLE
Rename default branch to devel

### ISSUE THREAD

**Issue by lgeistlinger** [OSCA-source/OSCA.advanced#14]
Hi @PeteHaitch @alanocallaghan @lshep

I'd like to rename the default branch of `OSCA.advanced` to `devel` following https://contributions.bioconductor.org/branch-rename-faqs.html, however I do not seem to have the permission to edit the default branch name (currently: `master`) here on the [github repo](https://github.com/OSCA-source/OSCA.advanced/branches). Can you please provide me with the permission to do so or alternatively perform the renaming of the default branch? Thanks!

**Comment by lshep** [comment]
I'm not sure who owns OSCA-source organization;  I currently do not have permissions on these repos to add you as collaborator.  Whomever is owner will have to do that.

**Comment by lgeistlinger** [comment]
Thanks. @LTLA @hpages maybe?

**Comment by hpages** [comment]
I changed your role from `Write` to `Maintain` @lgeistlinger. Let me know if you can rename the default branch now.

**Comment by lgeistlinger** [comment]
Thanks @hpages. Unfortunately not, I have permission to rename every branch except the default master branch that I am aiming to rename. 

<img width="1307" alt="Screenshot 2023-10-30 at 1 00 21 PM" src="https://github.com/OSCA-source/OSCA.advanced/assets/11871050/b7e0f71c-3435-4b38-9a3b-7c87d17c4fa3">

**Comment by hpages** [comment]
It seems that you already created a `devel` branch so I wouldn't expect that GitHub will let you rename `master` to `devel`. Either delete the `devel` branch first or try to make it the default?

**Comment by hpages** [comment]
BTW it seems that this `devel` branch is actually in sync with the `devel` branch on git.bioconductor.org so you should probably keep it and try to make it the default.

**Comment by lgeistlinger** [comment]
> It seems that you already created a devel branch so I wouldn't expect that GitHub will let you rename master to devel.

That is a good point, the main piece here however is that I don't have permission to rename the master branch at all (eg I could also not rename it to a non-existing branch name such as `foo`).

> so you should probably keep it and try to make it the default.

That is a good idea, but I also do not have permission for that. If I follow the [github docs for changing the default branch](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch), this needs to be done under settings in the "default branch" section. However, this is not listed when I go under settings here on `OSCA.advanced`:

<img width="1314" alt="Screenshot 2023-10-30 at 1 28 05 PM" src="https://github.com/OSCA-source/OSCA.advanced/assets/11871050/5d608c51-b5ff-4e23-99f3-c5bc08ef759f">

Compared to my own lgeistlinger/EnrichmentBrowser repo where the option to change the default branch is available:

<img width="1324" alt="Screenshot 2023-10-30 at 1 28 16 PM" src="https://github.com/OSCA-source/OSCA.advanced/assets/11871050/79ddaaa9-32c5-41d9-8a7f-de36b9224603">

**Comment by hpages** [comment]
I changed your role from `Maintain` to `Admin`. Hopefully with this change you'll be able to switch the default branch from `master` to `devel`.

**Comment by lgeistlinger** [comment]
Thanks. That did the trick!
