### ISSUE TITLE
Error in type.convert.default(as.character(data[[i]]), na.strings = na.strings, : invalid multibyte string at '<cd>ndi'

### ISSUE THREAD

**Issue by alvarojmartinez18** [OSCA-source/OSCA.advanced#8]
Hello everyone

I've been trying to solve a problem with the sqlQuery function from RODBC package.  The code is shown as follows:

`TERADATA <- odbcConnect("TERADATA", uid="***", pwd="***")`

`prices1 <- sqlQuery(TERADATA, paste("SELECT * FROM PRO_BR_VIEW.C_SIFVALPrecioTitulo", "WHERE Id_ISIN IN ('COJ1GCD00652','COB02CD30508','COB13CD03GX4','COJ26CB00051','COB13CD0RDZ3','COB13CD01F29','COB13CD0NZL5','COB07CD0AKJ6','COB02CD44970','COJ12CD0REL4','COB01CD0AJU1','COB13CD0QTF3','COB13CD01YN2','COB13CD0MDC3','COB13CD0QFV9','COB13CD0RDY6','COB19CD1KN08','COB01CD09LZ1','COB06CD15JP2','COB19CD1L0V9','COB13CD0NZK7','COB19CD1K9V1','COB02CD30854','COB07CD0DFS1','COB13CD03OR0','COB02CD31266','COB01CD0AIH0','COB13CD0O100','COB01CD09M42','COB01CD0AKK0','COB02CD29922','COB13CD0QQD4','COB02CD30938','COB19CD1HQY1','COB53CB00029','COB13CD02R99','COB07CD0DI67','COB13CD01KE0','COB56CD1IBE7','COB53CD02PG8','COB68CB00035','COB66CD65525','COB13CD0MDD1','COB07CD0DJB9','COB13CD0MF42','COB64CD03L50','COB19CD1HJI9','COB66CD63199','COB13CD01ZK5','COB01CD0AKM6','COJ12CD0RED1','COB02CD29377','COB13CD0QXM1','COB56CD1IU70','COB01CD05VF0','COB01CD09Z54','COB01CD05S57','COB01CD061T6','COB01CD05SE9','COB23CD15778','COB02CB00463','COB51CD02I44','COB12CD43609','COB23CB00600','COB06CB00498','COB01CD05TS7','COB07CD0C3J5','COB01CD05YO6','COL06CD18792','COB51CB00791','COB06CD10DE0','COB01CD05QZ8','COB13CD14897','COJ12CB00010','COB01CD09YD1','COB06CD17QM0','COB07CD44870','COB12CD40134','COB64CD56552','COB63CD0LXA6','COL06CD18867','COB01CD05ZH7','COL06CD18651','COB07CD43559','COB51CB00403','COB07CD06Q45','COB63CD0LV71','COB64CD099V6','COB01CD09UL2','COB07CD07V70','COB07CD43385') AND Fecha_Registro > '2021-10-27' AND Fecha_Registro < '2022-04-28' ORDER BY Id_ISIN, Fecha_Registro"))`

And the result is: Error in type.convert.default(as.character(data[[i]]), na.strings = na.strings, : invalid multibyte string at '<cd>ndi'

If somebody knows what's happening please help me! 

Ty

**Comment by PeteHaitch** [comment]
Closing as off-topic.
